// One local Supabase stack per agent, so no agent can reset or pollute another's database
// (PHASE15_PLAN.md "Each agent gets its own database"; LESSONS.md). The dev stack (`deck`,
// ports 543xx) belongs to the parent's device testing and is never touched by this script.
//
// GoTrue and PostgREST serve exactly one database each, so a cloned database (createdb -T) is
// enough for pgTAP but not for Playwright. Each agent therefore gets a small stack of its own,
// built from the same migrations and seed (the "template"): `reset` re-applies them.
//
//   node scripts/agent-stack.mjs up <agent>      start (or reuse) the agent's stack, write its env
//   node scripts/agent-stack.mjs reset <agent>   re-apply migrations + seed on that stack only
//   node scripts/agent-stack.mjs down <agent>    stop it (data volume kept)
//   node scripts/agent-stack.mjs env <agent>     rewrite .agents/<agent>/agent.env
//   node scripts/agent-stack.mjs status          list the agents and whether each is up
//
// Agents: build (the builder), rls (rls-auditor, pgTAP only), kidux (kid-ux-tester),
// parentux (parent-ux-tester). Everything lives in .agents/ (gitignored).
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const SUPA = join(ROOT, 'supabase');

// `digit` replaces the 4 in 543xx; `vite` is the agent's own app port on the Tailscale IP.
export const AGENTS = {
  build: { digit: 5, vite: 4010, api: true },
  kidux: { digit: 6, vite: 4011, api: true },
  parentux: { digit: 7, vite: 4012, api: true },
  rls: { digit: 8, vite: null, api: false },
};

// Services nobody's tests need. Studio, analytics and edge functions stay on the dev stack; storage stays (the grants audit checks its buckets).
const EXCLUDE_ALWAYS = ['studio', 'imgproxy', 'logflare', 'vector', 'supavisor', 'postgres-meta', 'edge-runtime'];
const EXCLUDE_NO_API = ['kong', 'postgrest', 'mailpit'];
const DISABLE_SECTIONS = new Set(['studio', 'analytics', 'edge_runtime', 'db.pooler']);
const LINKS = ['migrations', 'seed.sql', 'tests', 'checks', 'functions', 'snippets'];
// The CLI refuses email templates that resolve outside the workdir, so these are copied.
const COPIES = ['templates'];

function tailscaleIp() {
  if (process.env.DECK_HOST) return process.env.DECK_HOST;
  try {
    return execFileSync('tailscale', ['ip', '-4'], { encoding: 'utf8' }).trim().split('\n')[0];
  } catch {
    throw new Error('No Tailscale IP. Agents test on the Tailscale origin, never localhost (set DECK_HOST to override).');
  }
}

const dirOf = (name) => join(ROOT, '.agents', name);
const workdir = (name) => relative(ROOT, dirOf(name));

function agentConfig(name) {
  const a = AGENTS[name];
  const host = tailscaleIp();
  let section = '';
  const out = readFileSync(join(SUPA, 'config.toml'), 'utf8')
    .split('\n')
    .map((line) => {
      const header = /^\[([^\]]+)\]/.exec(line);
      if (header) section = header[1];
      if (/^project_id\s*=/.test(line)) return `project_id = "deck-${name}"`;
      if (/^site_url\s*=/.test(line)) return a.vite ? `site_url = "http://${host}:${a.vite}"` : line;
      if (/^\s*enabled\s*=/.test(line) && (DISABLE_SECTIONS.has(section) || (!a.api && section === 'local_smtp'))) return 'enabled = false';
      if (/^\s*inspector_port\s*=/.test(line)) return `inspector_port = ${8083 + a.digit * 10}`;
      return line.replace(/\b543(\d\d)\b/g, `5${a.digit}3$1`);
    });
  return `# Generated by scripts/agent-stack.mjs from supabase/config.toml. Do not edit.\n${out.join('\n')}`;
}

function scaffold(name) {
  const supa = join(dirOf(name), 'supabase');
  mkdirSync(supa, { recursive: true });
  writeFileSync(join(supa, 'config.toml'), agentConfig(name));
  for (const l of LINKS) {
    const target = join(SUPA, l);
    const link = join(supa, l);
    if (!existsSync(target)) continue;
    rmSync(link, { force: true, recursive: false });
    symlinkSync(relative(supa, target), link);
  }
  // Kong bind-mounts each template file. A copy that makes a new inode orphans the mount (the
  // templates then 404 and no sign-in code is sent), so write in place, and only on change.
  for (const c of COPIES) {
    mkdirSync(join(supa, c), { recursive: true });
    for (const f of readdirSync(join(SUPA, c))) {
      const body = readFileSync(join(SUPA, c, f));
      const dest = join(supa, c, f);
      if (!existsSync(dest) || !readFileSync(dest).equals(body)) writeFileSync(dest, body);
    }
  }
}

function supabase(name, args, opts = {}) {
  return execFileSync('supabase', [...args, '--workdir', workdir(name)], { stdio: opts.capture ? 'pipe' : 'inherit', encoding: 'utf8' });
}

function status(name) {
  try {
    const raw = supabase(name, ['status', '-o', 'json'], { capture: true });
    return JSON.parse(raw.replace(/^[^{]*/, ''));
  } catch {
    return null;
  }
}

function writeEnv(name) {
  const a = AGENTS[name];
  const s = status(name);
  if (!s) throw new Error(`deck-${name} is not running: node scripts/agent-stack.mjs up ${name}`);
  const host = tailscaleIp();
  const env = {
    DECK_AGENT: name,
    DECK_DB_CONTAINER: `supabase_db_deck-${name}`,
    DECK_DB_PORT: String(new URL(s.DB_URL).port),
    ...(a.api && {
      DECK_ORIGIN: `http://${host}:${a.vite}`,
      DECK_VITE_PORT: String(a.vite),
      DECK_MAILPIT: `http://${host}:5${a.digit}324`,
      VITE_SUPABASE_URL: `http://${host}:${new URL(s.API_URL).port}`,
      VITE_SUPABASE_ANON_KEY: s.ANON_KEY,
    }),
  };
  const body = Object.entries(env).map(([k, v]) => `${k}=${v}`).join('\n');
  writeFileSync(join(dirOf(name), 'agent.env'), `# Generated by scripts/agent-stack.mjs. Local-only keys; gitignored.\n${body}\n`);
  console.log(`.agents/${name}/agent.env -> ${env.DECK_ORIGIN ?? `db only, port ${env.DECK_DB_PORT}`}`);
}

function up(name) {
  scaffold(name);
  if (!status(name)) {
    const exclude = [...EXCLUDE_ALWAYS, ...(AGENTS[name].api ? [] : EXCLUDE_NO_API)];
    supabase(name, ['start', '-x', exclude.join(',')]);
  }
  writeEnv(name);
}

const [cmd, name] = process.argv.slice(2);
const need = () => {
  if (!AGENTS[name]) throw new Error(`agent must be one of: ${Object.keys(AGENTS).join(', ')}`);
};
switch (cmd) {
  case 'up':
    need();
    up(name);
    break;
  case 'reset':
    need();
    scaffold(name);
    supabase(name, ['db', 'reset']);
    writeEnv(name);
    break;
  case 'down':
    need();
    supabase(name, ['stop']);
    break;
  case 'env':
    need();
    writeEnv(name);
    break;
  case 'status':
    for (const n of Object.keys(AGENTS)) console.log(`${n.padEnd(9)} ${status(n) ? 'up' : 'down'}`);
    break;
  default:
    console.error('usage: node scripts/agent-stack.mjs up|reset|down|env <agent> | status');
    process.exit(1);
}
