"""Pack the self-hosted Fluent Emoji files the app uses into one sprite (art spec: build-sprite).

Reads src/art/manifest.json (the Fluent files that ship, 3D style: the parent's pick in Phase 1
slice 0) and their WebP files in public/art/fluent/, and writes:
  public/art/fluent/sprite.webp   every file on a grid of CELL px squares
  src/art/sprite.json             key -> { col, row } and the grid size
  src/styles/sprite.css           .fx-<key> background positions (the canvas's class names)

Run with the local venv: .venv/bin/python scripts/build-sprite.py   (npm run art:sprite)
"""
import json
import math
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CELL = 128
manifest = json.loads((ROOT / "src/art/manifest.json").read_text())
keys = sorted(manifest)
cols = math.ceil(math.sqrt(len(keys)))
rows = math.ceil(len(keys) / cols)

sheet = Image.new("RGBA", (cols * CELL, rows * CELL), (0, 0, 0, 0))
cells = {}
for i, key in enumerate(keys):
    img = Image.open(ROOT / f"public/art/fluent/{key}.webp").convert("RGBA")
    img.thumbnail((CELL, CELL), Image.LANCZOS)
    col, row = i % cols, i // cols
    sheet.paste(img, (col * CELL + (CELL - img.width) // 2, row * CELL + (CELL - img.height) // 2), img)
    cells[key] = {"col": col, "row": row}

sheet.save(ROOT / "public/art/fluent/sprite.webp", "WEBP", quality=86, alpha_quality=100, method=6)
(ROOT / "src/art/sprite.json").write_text(json.dumps({"cell": CELL, "cols": cols, "rows": rows, "cells": cells}, indent=2) + "\n")

pos = lambda i, n: "0%" if n == 1 else f"{i / (n - 1) * 100:.4f}%"
css = [
    "/* Generated by scripts/build-sprite.py. Do not edit. */",
    f".fx {{ background-image: url('/art/fluent/sprite.webp'); background-size: {cols * 100}% {rows * 100}%; background-repeat: no-repeat; display: block; flex-shrink: 0; }}",
]
css += [f".fx-{k} {{ background-position: {pos(c['col'], cols)} {pos(c['row'], rows)}; }}" for k, c in cells.items()]
(ROOT / "src/styles/sprite.css").write_text("\n".join(css) + "\n")
print(f"{len(keys)} files -> {cols}x{rows} sprite, {(ROOT / 'public/art/fluent/sprite.webp').stat().st_size // 1024} KiB")
