// Writes .env.local for local dev: the local Supabase API at the Mac's Tailscale IP (so the
// phone and iPad can reach it) and the local anon key from `supabase status`.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const status = JSON.parse(execFileSync('supabase', ['status', '-o', 'json'], { encoding: 'utf8' }).replace(/^[^{]*/, ''));
let ip = process.env.DECK_HOST;
if (!ip) {
  try {
    ip = execFileSync('tailscale', ['ip', '-4'], { encoding: 'utf8' }).trim().split('\n')[0];
  } catch {
    ip = '127.0.0.1';
  }
}
const port = new URL(status.API_URL).port;
writeFileSync(
  '.env.local',
  `# Generated by scripts/env-local.mjs. Local-only keys; gitignored.\nVITE_SUPABASE_URL=http://${ip}:${port}\nVITE_SUPABASE_ANON_KEY=${status.ANON_KEY}\n`,
);
console.log(`.env.local -> http://${ip}:${port}`);
